stages:
  - test
  - build
  - deploy

.merge_template: &merge_definition
  image: debian:buster-slim
  stage: build
  before_script:
    - apt-get update && apt-get install --no-install-suggests --no-install-recommends --yes gcc libpython3-dev python3-pip git
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/damsanx-do/system-deploy.git
    - chmod +x system-deploy/merge
  script:
    - ./system-deploy/merge

.deploy_template: &deploy_definition
  image: debian:buster-slim
  stage: deploy
  before_script:
    - apt-get update && apt-get install --no-install-suggests --no-install-recommends --yes gcc libpython3-dev python3-pip git python3-setuptools curl
    - pip3 install awscli
    - curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
    - chmod +x /usr/local/bin/ecs-cli
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/damsanx-do/system-deploy.git
    - chmod +x system-deploy/deploy
  script:
    - ./system-deploy/deploy

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache git bash
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/damsanx-do/system-deploy.git
    - chmod +x system-deploy/build
  script:
    - ./system-deploy/build
  only:
    - dev
    - master

#deploy_dev:
#  <<: *deploy_definition
#  only:
#    - dev
#  environment:
#    name: dev
#    url: https://data-advising.net/

merge_master_to_dev:
  <<: *merge_definition
  only:
    - master
  variables:
    MERGE_BRANCH_SRC: "master"
    MERGE_BRANCH_DEST: "dev"
